### ISSUE TITLE
java.awt.AWTError: Can't connect to X11 window server using ':0.0' as the value of the DISPLAY variable.

### ISSUE THREAD

**Issue by ripeyd** [erupts/erupt#118]
### 版本情况
Linux系统版本
LSB Version:    core-11.1.0ubuntu2-noarch:security-11.1.0ubuntu2-noarch
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.5 LTS
Release:        20.04
Codename:       focal

JDK版本
openjdk version "17.0.4" 2022-07-19
OpenJDK Runtime Environment GraalVM CE 22.2.0 (build 17.0.4+8-jvmci-22.2-b06)
OpenJDK 64-Bit Server VM GraalVM CE 22.2.0 (build 17.0.4+8-jvmci-22.2-b06, mixed mode, sharing)

erupt版本
:: Spring Boot     :: v(2.7.2)
:: Erupt Framework :: v(1.10.13) 

### 问题描述（包括截图）

堆栈信息
```
2022-09-07 12:26:06.609  INFO 35678 --- [           main] com.bacterial.strain.cms.CmsApplication  : Starting CmsApplication v1.0.0 using Java 17.0.4 on iZ2ze436qim4c2f4o4vsl9Z with PID 35678 (/var/www/strain/cms-1.0.0.jar started by root in /var/www/strain)
2022-09-07 12:26:06.612  INFO 35678 --- [           main] com.bacterial.strain.cms.CmsApplication  : The following 1 profile is active: "dev"
2022-09-07 12:26:09.953  INFO 35678 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Multiple Spring Data modules found, entering strict repository configuration mode
2022-09-07 12:26:09.967  INFO 35678 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data JPA repositories in DEFAULT mode.
2022-09-07 12:26:09.995  INFO 35678 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 8 ms. Found 0 JPA repository interfaces.
2022-09-07 12:26:10.074  INFO 35678 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Multiple Spring Data modules found, entering strict repository configuration mode
2022-09-07 12:26:10.079  INFO 35678 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data Redis repositories in DEFAULT mode.
2022-09-07 12:26:10.124  INFO 35678 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 1 ms. Found 0 Redis repository interfaces.
2022-09-07 12:26:12.656  INFO 35678 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8080 (http)
2022-09-07 12:26:12.682  INFO 35678 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2022-09-07 12:26:12.683  INFO 35678 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.65]
2022-09-07 12:26:12.932  INFO 35678 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2022-09-07 12:26:12.933  INFO 35678 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 6095 ms
2022-09-07 12:26:14.392  INFO 35678 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
2022-09-07 12:26:15.727  INFO 35678 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
2022-09-07 12:26:16.136  INFO 35678 --- [           main] o.hibernate.jpa.internal.util.LogHelper  : HHH000204: Processing PersistenceUnitInfo [name: default]
2022-09-07 12:26:16.770  INFO 35678 --- [           main] org.hibernate.Version                    : HHH000412: Hibernate ORM core version 5.6.10.Final
2022-09-07 12:26:17.592  INFO 35678 --- [           main] o.hibernate.annotations.common.Version   : HCANN000001: Hibernate Commons Annotations {5.1.2.Final}
2022-09-07 12:26:18.026  INFO 35678 --- [           main] org.hibernate.dialect.Dialect            : HHH000400: Using dialect: org.hibernate.dialect.MySQL5InnoDBDialect
2022-09-07 12:26:21.746  INFO 35678 --- [           main] o.h.e.t.j.p.i.JtaPlatformInitiator       : HHH000490: Using JtaPlatform implementation: [org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform]
2022-09-07 12:26:21.780  INFO 35678 --- [           main] j.LocalContainerEntityManagerFactoryBean : Initialized JPA EntityManagerFactory for persistence unit 'default'
2022-09-07 12:26:23.479  WARN 35678 --- [           main] JpaBaseConfiguration$JpaWebConfiguration : spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering. Explicitly configure spring.jpa.open-in-view to disable this warning
2022-09-07 12:26:24.132  INFO 35678 --- [           main] o.s.b.a.w.s.WelcomePageHandlerMapping    : Adding welcome page: class path resource [public/index.html]
2022-09-07 12:26:25.334  INFO 35678 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8080 (http) with context path ''
2022-09-07 12:26:25.385  INFO 35678 --- [           main] com.bacterial.strain.cms.CmsApplication  : Started CmsApplication in 20.89 seconds (JVM running for 25.34)
2022-09-07 12:26:25.674  INFO 35678 --- [           main] xyz.erupt.core.service.EruptCoreService  : <============================================================>
2022-09-07 12:26:25.681  INFO 35678 --- [           main] xyz.erupt.core.service.EruptCoreService  : 🚀 -> erupt-jpa      module initialization completed in 288ms
2022-09-07 12:26:25.686  INFO 35678 --- [           main] xyz.erupt.core.service.EruptCoreService  : 🚀 -> erupt-security module initialization completed in 5ms
2022-09-07 12:26:25.688  INFO 35678 --- [           main] xyz.erupt.core.service.EruptCoreService  : 🚀 -> erupt-upms     module initialization completed in 2ms
2022-09-07 12:26:25.690  INFO 35678 --- [           main] xyz.erupt.core.service.EruptCoreService  : Erupt modules : 3
2022-09-07 12:26:25.690  INFO 35678 --- [           main] xyz.erupt.core.service.EruptCoreService  : Erupt classes : 15
2022-09-07 12:26:25.690  INFO 35678 --- [           main] xyz.erupt.core.service.EruptCoreService  : Erupt Framework initialization completed in 297ms
2022-09-07 12:26:25.691  INFO 35678 --- [           main] xyz.erupt.core.service.EruptCoreService  : <============================================================>
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)
Caused by: java.awt.AWTError: Can't connect to X11 window server using ':0.0' as the value of the DISPLAY variable.
        at java.desktop/sun.awt.X11GraphicsEnvironment.initDisplay(Native Method)
        at java.desktop/sun.awt.X11GraphicsEnvironment$1.run(X11GraphicsEnvironment.java:101)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
        at java.desktop/sun.awt.X11GraphicsEnvironment.<clinit>(X11GraphicsEnvironment.java:60)
        at java.desktop/sun.awt.PlatformGraphicsInfo.createGE(PlatformGraphicsInfo.java:36)
        at java.desktop/java.awt.GraphicsEnvironment$LocalGE.createGE(GraphicsEnvironment.java:93)
        at java.desktop/java.awt.GraphicsEnvironment$LocalGE.<clinit>(GraphicsEnvironment.java:84)
        at java.desktop/java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:106)
        at java.desktop/sun.awt.X11.XToolkit.<clinit>(XToolkit.java:224)
        at java.desktop/sun.awt.PlatformGraphicsInfo.createToolkit(PlatformGraphicsInfo.java:40)
        at java.desktop/java.awt.Toolkit.getDefaultToolkit(Toolkit.java:599)
        at java.desktop/java.awt.Desktop.isDesktopSupported(Desktop.java:329)
        at java.desktop/java.awt.Desktop.getDesktop(Desktop.java:303)
        at com.bacterial.strain.cms.CmsApplication.main(CmsApplication.java:23)
        ... 8 more
```

**Comment by ripeyd** [comment]
解决方案
不能用jar包，在pom.xml文件中添加。
	<packaging>war</packaging>
