### ISSUE TITLE
启动 xyz.erupt.sample.EruptSampleApplication 报错

### ISSUE THREAD

**Issue by tanpenggood** [erupts/erupt#242]
### 版本情况

JDK版本： openjdk_8
erupt版本： master

### 问题描述（包括截图）

1. 启动`xyz.erupt.sample.EruptSampleApplication`报错

2. 堆栈信息

```
                             __
                            /\ \__
   __   _ __   __  __  _____\ \ __\
 / __ \/\  __\/\ \/\ \/\  __ \ \ \
/\  __/\ \ \/ \ \ \_\ \ \ \_\ \ \ \__
\ \____\\ \_\  \ \____/\ \ ___/\ \___\
 \/____/ \/_/   \/___/  \ \ \/  \/___/
                         \ \_\
                          \/_/

:: Spring Boot     :: v(2.7.10)
:: Erupt Framework :: v(1.12.10) 
2024-04-12 00:11:30.291  INFO 28697 --- [           main] xyz.erupt.sample.EruptSampleApplication  : Starting EruptSampleApplication using Java 1.8.0_402 on iosdeMBP with PID 28697 (/Users/ios/tcode/erupt/erupt-sample/target/classes started by ios in /Users/ios/tcode/erupt)
2024-04-12 00:11:30.294  INFO 28697 --- [           main] xyz.erupt.sample.EruptSampleApplication  : No active profile set, falling back to 1 default profile: "default"
2024-04-12 00:11:30.991  INFO 28697 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Multiple Spring Data modules found, entering strict repository configuration mode
2024-04-12 00:11:30.993  INFO 28697 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data JPA repositories in DEFAULT mode.
2024-04-12 00:11:31.007  INFO 28697 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 4 ms. Found 0 JPA repository interfaces.
2024-04-12 00:11:31.022  INFO 28697 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Multiple Spring Data modules found, entering strict repository configuration mode
2024-04-12 00:11:31.023  INFO 28697 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data Redis repositories in DEFAULT mode.
2024-04-12 00:11:31.031  INFO 28697 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 0 ms. Found 0 Redis repository interfaces.
2024-04-12 00:11:31.803  INFO 28697 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8080 (http)
2024-04-12 00:11:31.813  INFO 28697 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2024-04-12 00:11:31.814  INFO 28697 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.73]
2024-04-12 00:11:31.938  INFO 28697 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2024-04-12 00:11:31.938  INFO 28697 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 1596 ms
2024-04-12 00:11:31.969  INFO 28697 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
2024-04-12 00:11:32.371  INFO 28697 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
2024-04-12 00:11:32.382  INFO 28697 --- [           main] o.s.b.a.h2.H2ConsoleAutoConfiguration    : H2 console available at '/h2'. Database available at 'jdbc:h2:file:./erupt'
2024-04-12 00:11:32.883  INFO 28697 --- [           main] o.hibernate.jpa.internal.util.LogHelper  : HHH000204: Processing PersistenceUnitInfo [name: default]
2024-04-12 00:11:32.941  INFO 28697 --- [           main] org.hibernate.Version                    : HHH000412: Hibernate ORM core version 5.6.15.Final
2024-04-12 00:11:33.139  INFO 28697 --- [           main] o.hibernate.annotations.common.Version   : HCANN000001: Hibernate Commons Annotations {5.1.2.Final}
2024-04-12 00:11:33.244  INFO 28697 --- [           main] org.hibernate.dialect.Dialect            : HHH000400: Using dialect: org.hibernate.dialect.H2Dialect
Hibernate: alter table e_dict_item drop constraint if exists UKl0kiq8otpn3fvtlvarebt8xkh
Hibernate: alter table e_dict_item add constraint UKl0kiq8otpn3fvtlvarebt8xkh unique (code, erupt_dict_id)
2024-04-12 00:11:34.244  INFO 28697 --- [           main] o.h.e.t.j.p.i.JtaPlatformInitiator       : HHH000490: Using JtaPlatform implementation: [org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform]
2024-04-12 00:11:34.252  INFO 28697 --- [           main] j.LocalContainerEntityManagerFactoryBean : Initialized JPA EntityManagerFactory for persistence unit 'default'
2024-04-12 00:11:34.593  WARN 28697 --- [           main] JpaBaseConfiguration$JpaWebConfiguration : spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering. Explicitly configure spring.jpa.open-in-view to disable this warning
Hibernate: /*  from CloudNode */ select cloudnode0_.id as id1_0_, cloudnode0_.create_by as create_b2_0_, cloudnode0_.create_time as create_t3_0_, cloudnode0_.update_by as update_b4_0_, cloudnode0_.update_time as update_t5_0_, cloudnode0_.access_token as access_t6_0_, cloudnode0_.cloud_node_group_id as cloud_n13_0_, cloudnode0_.config as config7_0_, cloudnode0_.duty as duty8_0_, cloudnode0_.name as name9_0_, cloudnode0_.node_name as node_na10_0_, cloudnode0_.remark as remark11_0_, cloudnode0_.status as status12_0_ from e_cloud_node cloudnode0_
2024-04-12 00:11:34.846  INFO 28697 --- [           main] o.s.b.a.w.s.WelcomePageHandlerMapping    : Adding welcome page: class path resource [public/index.html]
2024-04-12 00:11:35.163  WARN 28697 --- [           main] o.s.b.a.f.FreeMarkerAutoConfiguration    : Cannot find template location(s): [classpath:/templates/] (please add some templates, check your FreeMarker configuration, or set spring.freemarker.check-template-location=false)
2024-04-12 00:11:35.239  INFO 28697 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8080 (http) with context path ''
2024-04-12 00:11:35.253  INFO 28697 --- [           main] xyz.erupt.sample.EruptSampleApplication  : Started EruptSampleApplication in 5.586 seconds (JVM running for 6.217)
2024-04-12 00:11:35.354  INFO 28697 --- [           main] xyz.erupt.core.service.EruptCoreService  : <============================================================>
2024-04-12 00:11:35.356  INFO 28697 --- [           main] xyz.erupt.core.service.EruptCoreService  : 🚀 -> erupt-cloud-server module initialization completed in 100ms
2024-04-12 00:11:35.356  INFO 28697 --- [           main] xyz.erupt.core.service.EruptCoreService  : 🚀 -> erupt-jpa          module initialization completed in 0ms
2024-04-12 00:11:35.356  INFO 28697 --- [           main] xyz.erupt.core.service.EruptCoreService  : 🚀 -> erupt-security     module initialization completed in 0ms
2024-04-12 00:11:35.377  INFO 28697 --- [           main] xyz.erupt.core.service.EruptCoreService  : 🚀 -> erupt-tpl          module initialization completed in 21ms
2024-04-12 00:11:35.377  INFO 28697 --- [           main] xyz.erupt.core.service.EruptCoreService  : 🚀 -> erupt-upms         module initialization completed in 0ms
2024-04-12 00:11:35.377  INFO 28697 --- [           main] xyz.erupt.core.service.EruptCoreService  : Erupt modules : 5
2024-04-12 00:11:35.377  INFO 28697 --- [           main] xyz.erupt.core.service.EruptCoreService  : Erupt classes : 16
2024-04-12 00:11:35.378  INFO 28697 --- [           main] xyz.erupt.core.service.EruptCoreService  : Erupt Framework initialization completed in 122ms
2024-04-12 00:11:35.378  INFO 28697 --- [           main] xyz.erupt.core.service.EruptCoreService  : <============================================================>
Hibernate: /* dynamic native SQL query */ select count(*) from e_upms_user
Hibernate: /*  from EruptMenu where code =  :val */ select eruptmenu0_.id as id1_5_, eruptmenu0_.create_by as create_b2_5_, eruptmenu0_.create_time as create_t3_5_, eruptmenu0_.update_by as update_b4_5_, eruptmenu0_.update_time as update_t5_5_, eruptmenu0_.code as code6_5_, eruptmenu0_.icon as icon7_5_, eruptmenu0_.name as name8_5_, eruptmenu0_.param as param9_5_, eruptmenu0_.parent_menu_id as parent_14_5_, eruptmenu0_.sort as sort10_5_, eruptmenu0_.status as status11_5_, eruptmenu0_.type as type12_5_, eruptmenu0_.value as value13_5_ from e_upms_menu eruptmenu0_ where eruptmenu0_.code=?
2024-04-12 00:11:35.455  WARN 28697 --- [           main] o.h.engine.jdbc.spi.SqlExceptionHelper   : SQL Error: 42001, SQLState: 42001
2024-04-12 00:11:35.456 ERROR 28697 --- [           main] o.h.engine.jdbc.spi.SqlExceptionHelper   : Syntax error in SQL statement "/*  from EruptMenu where code =  :val */ select eruptmenu0_.id as id1_5_, eruptmenu0_.create_by as create_b2_5_, eruptmenu0_.create_time as create_t3_5_, eruptmenu0_.update_by as update_b4_5_, eruptmenu0_.update_time as update_t5_5_, eruptmenu0_.code as code6_5_, eruptmenu0_.icon as icon7_5_, eruptmenu0_.name as name8_5_, eruptmenu0_.param as param9_5_, eruptmenu0_.parent_menu_id as parent_14_5_, eruptmenu0_.sort as sort10_5_, eruptmenu0_.status as status11_5_, eruptmenu0_.type as type12_5_, eruptmenu0_.[*]value as value13_5_ from e_upms_menu eruptmenu0_ where eruptmenu0_.code=?"; expected "identifier"; SQL statement:
/*  from EruptMenu where code =  :val */ select eruptmenu0_.id as id1_5_, eruptmenu0_.create_by as create_b2_5_, eruptmenu0_.create_time as create_t3_5_, eruptmenu0_.update_by as update_b4_5_, eruptmenu0_.update_time as update_t5_5_, eruptmenu0_.code as code6_5_, eruptmenu0_.icon as icon7_5_, eruptmenu0_.name as name8_5_, eruptmenu0_.param as param9_5_, eruptmenu0_.parent_menu_id as parent_14_5_, eruptmenu0_.sort as sort10_5_, eruptmenu0_.status as status11_5_, eruptmenu0_.type as type12_5_, eruptmenu0_.value as value13_5_ from e_upms_menu eruptmenu0_ where eruptmenu0_.code=? [42001-214]
2024-04-12 00:11:35.467  INFO 28697 --- [           main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2024-04-12 00:11:35.516 ERROR 28697 --- [           main] o.s.boot.SpringApplication               : Application run failed

java.lang.IllegalStateException: Failed to execute CommandLineRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:771) [spring-boot-2.7.10.jar:2.7.10]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:752) [spring-boot-2.7.10.jar:2.7.10]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:314) [spring-boot-2.7.10.jar:2.7.10]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1303) [spring-boot-2.7.10.jar:2.7.10]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1292) [spring-boot-2.7.10.jar:2.7.10]
	at xyz.erupt.sample.EruptSampleApplication.main(EruptSampleApplication.java:14) [classes/:na]
Caused by: javax.persistence.PersistenceException: org.hibernate.exception.SQLGrammarException: could not prepare statement
	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:154) ~[hibernate-core-5.6.15.Final.jar:5.6.15.Final]
	at org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1626) ~[hibernate-core-5.6.15.Final.jar:5.6.15.Final]
	at org.hibernate.query.internal.AbstractProducedQuery.getSingleResult(AbstractProducedQuery.java:1665) ~[hibernate-core-5.6.15.Final.jar:5.6.15.Final]
	at xyz.erupt.jpa.dao.EruptDao.queryEntity(EruptDao.java:154) ~[classes/:na]
	at xyz.erupt.jpa.dao.EruptDao.persistIfNotExist(EruptDao.java:104) ~[classes/:na]
	at xyz.erupt.upms.service.UpmsDataLoadService.lambda$null$2(UpmsDataLoadService.java:67) ~[classes/:na]
	at xyz.erupt.upms.service.UpmsDataLoadService.lambda$null$3(UpmsDataLoadService.java:94) ~[classes/:na]
	at xyz.erupt.core.util.ProjectUtil.projectStartLoaded(ProjectUtil.java:37) ~[classes/:na]
	at xyz.erupt.upms.service.UpmsDataLoadService.lambda$null$4(UpmsDataLoadService.java:63) ~[classes/:na]
	at java.util.Optional.ifPresent(Optional.java:159) ~[na:1.8.0_402]
	at xyz.erupt.upms.service.UpmsDataLoadService.lambda$run$5(UpmsDataLoadService.java:62) ~[classes/:na]
	at xyz.erupt.core.module.EruptModuleInvoke.lambda$invoke$0(EruptModuleInvoke.java:22) ~[classes/:na]
	at java.util.ArrayList.forEach(ArrayList.java:1259) ~[na:1.8.0_402]
	at xyz.erupt.core.module.EruptModuleInvoke.invoke(EruptModuleInvoke.java:22) ~[classes/:na]
	at xyz.erupt.upms.service.UpmsDataLoadService.run(UpmsDataLoadService.java:62) ~[classes/:na]
	at xyz.erupt.upms.service.UpmsDataLoadService$$FastClassBySpringCGLIB$$56e45395.invoke(<generated>) ~[classes/:na]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.26.jar:5.3.26]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793) ~[spring-aop-5.3.26.jar:5.3.26]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.3.26.jar:5.3.26]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.3.26.jar:5.3.26]
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123) ~[spring-tx-5.3.26.jar:5.3.26]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388) ~[spring-tx-5.3.26.jar:5.3.26]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119) ~[spring-tx-5.3.26.jar:5.3.26]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.26.jar:5.3.26]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.3.26.jar:5.3.26]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708) ~[spring-aop-5.3.26.jar:5.3.26]
	at xyz.erupt.upms.service.UpmsDataLoadService$$EnhancerBySpringCGLIB$$fd5f48eb.run(<generated>) ~[classes/:na]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:768) [spring-boot-2.7.10.jar:2.7.10]
	... 5 common frames omitted
Caused by: org.hibernate.exception.SQLGrammarException: could not prepare statement
	at org.hibernate.exception.internal.SQLExceptionTypeDelegate.convert(SQLExceptionTypeDelegate.java:63) ~[hibernate-core-5.6.15.Final.jar:5.6.15.Final]
	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:37) ~[hibernate-core-5.6.15.Final.jar:5.6.15.Final]
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:113) ~[hibernate-core-5.6.15.Final.jar:5.6.15.Final]
	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$StatementPreparationTemplate.prepareStatement(StatementPreparerImpl.java:186) ~[hibernate-core-5.6.15.Final.jar:5.6.15.Final]
	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl.prepareQueryStatement(StatementPreparerImpl.java:151) ~[hibernate-core-5.6.15.Final.jar:5.6.15.Final]
	at org.hibernate.loader.Loader.prepareQueryStatement(Loader.java:2122) ~[hibernate-core-5.6.15.Final.jar:5.6.15.Final]
	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:2059) ~[hibernate-core-5.6.15.Final.jar:5.6.15.Final]
	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:2037) ~[hibernate-core-5.6.15.Final.jar:5.6.15.Final]
	at org.hibernate.loader.Loader.doQuery(Loader.java:956) ~[hibernate-core-5.6.15.Final.jar:5.6.15.Final]
	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:357) ~[hibernate-core-5.6.15.Final.jar:5.6.15.Final]
	at org.hibernate.loader.Loader.doList(Loader.java:2868) ~[hibernate-core-5.6.15.Final.jar:5.6.15.Final]
	at org.hibernate.loader.Loader.doList(Loader.java:2850) ~[hibernate-core-5.6.15.Final.jar:5.6.15.Final]
	at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2682) ~[hibernate-core-5.6.15.Final.jar:5.6.15.Final]
	at org.hibernate.loader.Loader.list(Loader.java:2677) ~[hibernate-core-5.6.15.Final.jar:5.6.15.Final]
	at org.hibernate.loader.hql.QueryLoader.list(QueryLoader.java:540) ~[hibernate-core-5.6.15.Final.jar:5.6.15.Final]
	at org.hibernate.hql.internal.ast.QueryTranslatorImpl.list(QueryTranslatorImpl.java:400) ~[hibernate-core-5.6.15.Final.jar:5.6.15.Final]
	at org.hibernate.engine.query.spi.HQLQueryPlan.performList(HQLQueryPlan.java:218) ~[hibernate-core-5.6.15.Final.jar:5.6.15.Final]
	at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1459) ~[hibernate-core-5.6.15.Final.jar:5.6.15.Final]
	at org.hibernate.query.internal.AbstractProducedQuery.doList(AbstractProducedQuery.java:1649) ~[hibernate-core-5.6.15.Final.jar:5.6.15.Final]
	at org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1617) ~[hibernate-core-5.6.15.Final.jar:5.6.15.Final]
	... 31 common frames omitted
Caused by: org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "/*  from EruptMenu where code =  :val */ select eruptmenu0_.id as id1_5_, eruptmenu0_.create_by as create_b2_5_, eruptmenu0_.create_time as create_t3_5_, eruptmenu0_.update_by as update_b4_5_, eruptmenu0_.update_time as update_t5_5_, eruptmenu0_.code as code6_5_, eruptmenu0_.icon as icon7_5_, eruptmenu0_.name as name8_5_, eruptmenu0_.param as param9_5_, eruptmenu0_.parent_menu_id as parent_14_5_, eruptmenu0_.sort as sort10_5_, eruptmenu0_.status as status11_5_, eruptmenu0_.type as type12_5_, eruptmenu0_.[*]value as value13_5_ from e_upms_menu eruptmenu0_ where eruptmenu0_.code=?"; expected "identifier"; SQL statement:
/*  from EruptMenu where code =  :val */ select eruptmenu0_.id as id1_5_, eruptmenu0_.create_by as create_b2_5_, eruptmenu0_.create_time as create_t3_5_, eruptmenu0_.update_by as update_b4_5_, eruptmenu0_.update_time as update_t5_5_, eruptmenu0_.code as code6_5_, eruptmenu0_.icon as icon7_5_, eruptmenu0_.name as name8_5_, eruptmenu0_.param as param9_5_, eruptmenu0_.parent_menu_id as parent_14_5_, eruptmenu0_.sort as sort10_5_, eruptmenu0_.status as status11_5_, eruptmenu0_.type as type12_5_, eruptmenu0_.value as value13_5_ from e_upms_menu eruptmenu0_ where eruptmenu0_.code=? [42001-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:502) ~[h2-2.1.214.jar:2.1.214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477) ~[h2-2.1.214.jar:2.1.214]
	at org.h2.message.DbException.getSyntaxError(DbException.java:261) ~[h2-2.1.214.jar:2.1.214]
	at org.h2.command.Parser.readIdentifier(Parser.java:5656) ~[h2-2.1.214.jar:2.1.214]
	at org.h2.command.Parser.readTermObjectDot(Parser.java:4838) ~[h2-2.1.214.jar:2.1.214]
	at org.h2.command.Parser.readTermWithIdentifier(Parser.java:5213) ~[h2-2.1.214.jar:2.1.214]
	at org.h2.command.Parser.readTerm(Parser.java:4901) ~[h2-2.1.214.jar:2.1.214]
	at org.h2.command.Parser.readFactor(Parser.java:3398) ~[h2-2.1.214.jar:2.1.214]
	at org.h2.command.Parser.readSum(Parser.java:3385) ~[h2-2.1.214.jar:2.1.214]
	at org.h2.command.Parser.readConcat(Parser.java:3350) ~[h2-2.1.214.jar:2.1.214]
	at org.h2.command.Parser.readCondition(Parser.java:3132) ~[h2-2.1.214.jar:2.1.214]
	at org.h2.command.Parser.readExpression(Parser.java:3053) ~[h2-2.1.214.jar:2.1.214]
	at org.h2.command.Parser.parseSelectExpressions(Parser.java:2853) ~[h2-2.1.214.jar:2.1.214]
	at org.h2.command.Parser.parseSelect(Parser.java:2871) ~[h2-2.1.214.jar:2.1.214]
	at org.h2.command.Parser.parseQueryPrimary(Parser.java:2762) ~[h2-2.1.214.jar:2.1.214]
	at org.h2.command.Parser.parseQueryTerm(Parser.java:2633) ~[h2-2.1.214.jar:2.1.214]
	at org.h2.command.Parser.parseQueryExpressionBody(Parser.java:2612) ~[h2-2.1.214.jar:2.1.214]
	at org.h2.command.Parser.parseQueryExpressionBodyAndEndOfQuery(Parser.java:2605) ~[h2-2.1.214.jar:2.1.214]
	at org.h2.command.Parser.parseQueryExpression(Parser.java:2598) ~[h2-2.1.214.jar:2.1.214]
	at org.h2.command.Parser.parseQuery(Parser.java:2567) ~[h2-2.1.214.jar:2.1.214]
	at org.h2.command.Parser.parsePrepared(Parser.java:724) ~[h2-2.1.214.jar:2.1.214]
	at org.h2.command.Parser.parse(Parser.java:689) ~[h2-2.1.214.jar:2.1.214]
	at org.h2.command.Parser.parse(Parser.java:661) ~[h2-2.1.214.jar:2.1.214]
	at org.h2.command.Parser.prepareCommand(Parser.java:569) ~[h2-2.1.214.jar:2.1.214]
	at org.h2.engine.SessionLocal.prepareLocal(SessionLocal.java:631) ~[h2-2.1.214.jar:2.1.214]
	at org.h2.engine.SessionLocal.prepareCommand(SessionLocal.java:554) ~[h2-2.1.214.jar:2.1.214]
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1116) ~[h2-2.1.214.jar:2.1.214]
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:92) ~[h2-2.1.214.jar:2.1.214]
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:288) ~[h2-2.1.214.jar:2.1.214]
	at com.zaxxer.hikari.pool.ProxyConnection.prepareStatement(ProxyConnection.java:337) ~[HikariCP-4.0.3.jar:na]
	at com.zaxxer.hikari.pool.HikariProxyConnection.prepareStatement(HikariProxyConnection.java) ~[HikariCP-4.0.3.jar:na]
	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$5.doPrepare(StatementPreparerImpl.java:149) ~[hibernate-core-5.6.15.Final.jar:5.6.15.Final]
	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$StatementPreparationTemplate.prepareStatement(StatementPreparerImpl.java:176) ~[hibernate-core-5.6.15.Final.jar:5.6.15.Final]
	... 47 common frames omitted

2024-04-12 00:11:36.541  INFO 28697 --- [           main] j.LocalContainerEntityManagerFactoryBean : Closing JPA EntityManagerFactory for persistence unit 'default'
2024-04-12 00:11:36.556  INFO 28697 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
2024-04-12 00:11:36.572  INFO 28697 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
```

4. 测试涉及到的文件（注意脱密）

**Comment by erupts** [comment]
建议先切换数据源到 mysql
